---

#- name: connect through ssh from local
#  local_action: command ssh -oBatchMode=yes root@{{ansible_host}} who
#  changed_when: False
#  register: who

#- name: check hostcode
#  slurp:
#    src: /etc/hostcode
#  register: hostcode
#  when: not hetzner_installimage_ignore_hostcode == 'yes'
#  ignore_errors: trues

#- debug:
#  msg: "{{ hostcode['content'] | b64decode }}"

- name: check the current rescue mode state
  local_action: uri
    url=https://robot-ws.your-server.de/boot/{{ hetzner_server_ip }}/rescue
    method=GET
    user={{ hetzner_installimage_webservice_username }}
    password={{ hetzner_installimage_webservice_password }}
    force_basic_auth=yes
    status_code=200
  register: hetzner_installimage_rescue
  when: hetzner_installimage_run

- name: include rescue mode
  include: rescuemode.yml
  when: hetzner_installimage_run and hetzner_installimage_rescue.json.rescue.active == false and not ansible_check_mode

- name: include installimage
  include: installimage.yml
  when: hetzner_installimage_run and hetzner_installimage_rescue.json.rescue.active == false and not ansible_check_mode

...
